---
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass-github
  annotations:
    tekton.dev/git-0: https://github.com # Described below
type: kubernetes.io/basic-auth
stringData:
  username: YOUR_GITHUB_USERNAME
  password: YOUR_GITHUB_PASSWORD
